[build]
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://agfzhwyhrrcbadbzvmpy.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZnpod3locnJjYmFkYnp2bXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4MzU3ODUsImV4cCI6MjEwNTQxMTc4NX0.WhUxOHsGYOHkad86--jDbiD6EmBNnoh8pDXHQwbQOpE"
  NEXT_PUBLIC_OWNER_EMAIL = "Omar.khallil@outlook.com"
  NEXT_PUBLIC_SITE_URL = "https://edge-log-11.netlify.app"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://edge-log-11.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://edge-log-11.netlify.app"

[context.branch-deploy.environment]
  NEXT_PUBLIC_SITE_URL = "https://edge-log-11.netlify.app"

[context.dev.environment]
  NEXT_PUBLIC_SITE_URL = "https://edge-log-11.netlify.app"

[dev]
  command = "npm run dev"
  targetPort = 3001
  framework = "next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
